### ISSUE TITLE
Remove Quotes when copy to clipboard is used

### ISSUE THREAD

**Issue by lababidi** [TexteaInc/json-viewer#271]
When I click "Copy to Clipboard" the text that's copied also includes the quotes from the json. Is there a way to disable that? I don't think anyone wants the quotes.

**Comment by pionxzh** [comment]
This is the expected behavior. It will copy the target "value".
[mac-s-g/react-json-view](https://github.com/mac-s-g/react-json-view) also presents same behavior.
If you really want to stripe those quotes, you can customize the behavior by providing an `onCopy` callback.

**Comment by pushchris** [comment]
This is quite an annoying functionality as for many use cases the user rarely wants to actually copy the quotes. Can you at least expose `useClipboard` so that you can intercept values just for strings but then use the same logic for everything else?  As it stands you have to re-write quite a bit of functionality just to address this

**Comment by pionxzh** [comment]
@pushchris How about adding the copy functionality as a third argument in the JsonViewerOnCopy type definition.
```diff
- export type JsonViewerOnCopy = <U = unknown>(path: Path, value: U) => unknown | Promise<unknown>
+ export type JsonViewerOnCopy = <U = unknown>(path: Path, value: U, copy: (value: string) => void) => unknown | Promise<unknown>
```
Additionally, exposing the `stringify` function so that users don't have to implement everything just to override a small part of it.

**Comment by pushchris** [comment]
That would be an excellent solution! Would make it way easier to extend for other use cases too! Good thinking
