### ISSUE TITLE
MUI v6 support

### ISSUE THREAD

**Issue by whtthfck** [TexteaInc/json-viewer#511]
Will there be support for @mui/materiel Version 6?

**Comment by pionxzh** [comment]
The breaking changes looks ok. I will arrange the testing recently. We might bump the major if we couldn't find a way to make it support both v5 and v6. Also, the browser or react version limits all need to be reviewed.

Another goal I want to achieve is completely removing MUI from this library to reduce the package size. But due to the limited time and resources I have for now, I might choose to publish the v6 version first.

**Comment by pionxzh** [comment]
V4 has been released. 🙏
